Repository istio/cni, pull requests merged in 2019-10, with the labels that each got.

#185 Local environment target cleanup
  Makefile
  Makefile.core.mk
  scripts/check_license.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: cla: yes, size/L

#187 Expunge circleci from cni repo
  .circleci/Dockerfile
  .circleci/config.yml
  .circleci/run_e2e.sh
  test/README.md
Labels: cla: yes, size/L

#189 Delete a superfluous file.
  .golangci.yml
Labels: cla: yes, size/L

#190 Enable the build container by default.
  Makefile.core.mk
  Makefile.overrides.mk
Labels: cla: yes, size/S

#186 Use su-sxec to chown /home within build container
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  test/prow-e2e.sh
Labels: cla: yes, size/M

#192 Use net=host to permit e2e to run.
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
  test/prow-e2e.sh
Labels: cla: yes, size/S

#193 Rename prow-e2e to e2e
  Makefile.core.mk
  test/e2e.sh
Labels: cla: yes, size/XS

#194 Make `test` work properly
  Makefile
  Makefile.core.mk
Labels: cla: yes, size/S

#196 Put override in correct place and remove su-exec
  Makefile
  Makefile.core.mk
  Makefile.overrides.mk
  common/.commonfiles.sha
Labels: cla: yes, size/S

#199 Record logs from e2e tests in event of failure
  test/e2e.sh
Labels: cla: yes, size/XS

#197 Delete an unused script.
  bin/check_shell_scripts.sh
Labels: cla: yes, size/M

#200 Update common files
  Makefile
  Makefile.overrides.mk
  common/.commonfiles.sha
Labels: cla: yes, size/M

#202 Release 1.4 codeowners
  CODEOWNERS
  Makefile
  README.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
  test/install_k8s_test.go
  tools/istio-cni-docker.mk
Labels: cla: yes, size/M

#203 Sync istio-iptables.sh with istio/istio:master
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/L

#205 Expand "CNI" initialism in README
  README.md
Labels: cla: yes, size/XS

#204 Sync istio-iptables.sh with istio/istio:release-1.4
  test/e2e.sh
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/L

#207 Update to common-files to implement docker.push
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cherrypick/release-1.4, cla: yes, size/M

#211 [release-1.4] Lower priorityClassName on istio-cni-node
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cla: yes, size/XS

#210 [release-1.3] Lower priorityClassName on istio-cni-node
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cla: yes, size/XS

#206 Allow to set custom annotations on pod level
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
Labels: cherrypick/release-1.4, cla: yes, ok-to-test, size/S

#214 Update gen and gen-check targets to match expected semanrtics.
  Makefile.core.mk
Labels: cla: yes, size/XS
