Repository istio/cni, pull requests merged in 2019-12, with the labels that each got.

#222 common-files update master-2019-11-26T07-29-27
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/S

#223 Return an error upon fail to obtain pod info
  cmd/istio-cni/main.go
Labels: cla: yes, size/M

#224 Sync istio-iptables.sh from istio/istio
  README.md
  tools/istio-cni-docker.mk
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/L

#228 Update common files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
Labels: cla: yes, size/M
