Repository istio/cni, pull requests merged in 2019-11, with the labels that each got.

#215 [release-1.4] Allow to set custom annotations on pod level
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
Labels: cla: yes, size/S

#118 Make file modifications atomic in install-cni.sh
  deployments/kubernetes/install/scripts/install-cni.sh
Labels: cla: yes

#216 [release-1.4] Make file modifications atomic in install-cni.sh
  deployments/kubernetes/install/scripts/install-cni.sh
Labels: cla: yes, size/M

#217 Update Istio dependencies
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  go.mod
  go.sum
  licenses/golang.org/x/tools/third_party/moduleloader/LICENSE
  licenses/golang.org/x/tools/third_party/typescript/LICENSE
  licenses/golang.org/x/tools/third_party/webcomponents/LICENSE
  licenses/istio.io/gogo-genproto/LICENSE
Labels: cla: yes, size/L

#218 Exclude pod if istio-init container is present
  README.md
  cmd/istio-cni/kubernetes.go
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
Labels: cla: yes, size/M

#219 Exclude pod if istio-init container is present
  README.md
  cmd/istio-cni/kubernetes.go
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
Labels: cla: yes, size/M

#220 Fix TestCmdAddExcludePodWithIstioInitContainer unit test
  cmd/istio-cni/main_test.go
Labels: cla: yes, size/XS
