Repository istio/cni, pull requests merged in 2019-09, with the labels that each got.

#168 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#166 [release-1.3] Use istio.io/api/annotations to reference pod annotation redirect params
  cmd/istio-cni/main.go
  cmd/istio-cni/redirect.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#169 Update common files
  .gitattributes
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L

#170 Enable all linters on this repo.
  Makefile.core.mk
  README.md
  common/Makefile.common.mk
  test/README.md
Labels: cla: yes, size/L

#171 Update common files.
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#172 Disable retrying ip6tables cleanup when IPv6 is disabled
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cherrypick/release-1.3, cla: yes, size/S

#176 Fix CircleCI branches used in release-1.3 tests
  .circleci/config.yml
  .circleci/run_e2e.sh
Labels: cla: yes, size/S

#173 [release-1.3] Disable retrying ip6tables cleanup when IPv6 is disabled
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/S

#178 Update common files and fix a linter warning.
  Makefile
  cmd/istio-cni/main.go
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
Labels: cla: yes, size/S

#175 Add the possibility to create RoleBinding for PSP
  README.md
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
Labels: cla: yes, size/S

#184 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L

#183 Enable build-tools within CNI repository
  Makefile.core.mk
  test/prow-e2e.sh
  tools/istio-cni-docker.mk
Labels: cla: yes, size/S
