Repository istio/cni, pull requests merged in 2019-08, with the labels that each got.

#138 Remove myself from CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#137 Update to apps/v1
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cla: yes, size/XS

#139 Test PR
  Makefile
Labels: cla: yes, size/XS

#140 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: area/test and release, cla: yes, size/XS

#143 Add prow e2e script
  Makefile
  test/prow-e2e.sh
Labels: cla: yes, size/M

#144 This repo is now managed by Tide, so delete mergify stuff.
  .mergify.yml
  README.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#145 [release-1.3] This repo is now managed by Tide, so delete mergify stuff.
  .mergify.yml
  README.md
Labels: cla: yes, size/S

#148 Update circleci image
  .circleci/Dockerfile
  .circleci/config.yml
Labels: cla: yes, size/XS

#149 Remove circle steps covered by prow
  .circleci/config.yml
Labels: cla: yes, size/M

#141 Make use of RBAC v1
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/XS

#151 [release-1.3] Add prow e2e script
  Makefile
  test/prow-e2e.sh
Labels: cla: yes, size/M

#150 Use release-1.3 tag for release-1.3 branch
  README.md
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
  test/install_k8s_test.go
  test/prow-e2e.sh
  tools/istio-cni-docker.mk
Labels: cla: yes, size/S

#153 [release-1.3] Update circleci image
  .circleci/Dockerfile
  .circleci/config.yml
Labels: cla: yes, size/XS

#154 [release-1.3] Remove circle steps covered by prow
  .circleci/config.yml
Labels: cla: yes, size/M

#155 [release-1.3] Make use of RBAC v1
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cla: yes, size/XS

#157 Update istio-iptables.sh in release-1.3
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/M

#156 Update istio-iptables.sh in master
  tools/packaging/common/iptables-retry.diff
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/M

#160 Update Helm version to magic tag to enable rewrite during release
  deployments/kubernetes/install/helm/istio-cni/Chart.yaml
Labels: cherrypick/release-1.3, cla: yes, size/XS

#161 [release-1.3] Update Helm version to magic tag to enable rewrite during release
  deployments/kubernetes/install/helm/istio-cni/Chart.yaml
Labels: cla: yes, size/XS

#163 Update common files.
  .circleci/Dockerfile
  .circleci/run_e2e.sh
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  README.md
  bin/.spelling_failures
  bin/check_license.sh
  bin/check_spelling.sh
  bin/init_helm.sh
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/report_build_info.sh
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/scripts/install-cni.sh
  deployments/kubernetes/install/test/data/env_vars.sh
  scripts/run_gobindata.sh
  tools/istio-cni-docker.mk
Labels: cla: yes, size/XL
