Repository istio/cni, pull requests merged in 2019-07, with the labels that each got.

#131 Tables interface
  cmd/istio-cni/iptables.go
  cmd/istio-cni/main.go
  cmd/istio-cni/redirect.go
Labels: size/L

#133 Add plugin config option to select InterceptRuleMgr type
  Makefile
  cmd/istio-cni/intercept_rule_mgr.go
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: size/L

#130 Remove outdated istio-cni*.yaml manifests
  README.md
  deployments/kubernetes/install/manifests/istio-cni.yaml
  deployments/kubernetes/install/manifests/istio-cni_gke.yaml
Labels: action/merge-to-release-branch

#135 circleci: pin KDC version
  .circleci/config.yml
Labels: cla: yes, size/XS
