Repository istio/cni, pull requests merged in 2020-01, with the labels that each got.

#225 Donot redirect app calls back to itself by podip via envoy
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/M

#226 Adding CNI Repair Daemonset
  Makefile.core.mk
  cmd/istio-cni-repair/README.md
  cmd/istio-cni-repair/main.go
  deployments/kubernetes/Dockerfile.install-cni
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  go.mod
  go.sum
  licenses/github.com/docopt/docopt-go/LICENSE
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
  tools/istio-cni-docker.mk
Labels: cla: yes, size/XXL

#229 Parameterizing the init container name
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
Labels: cla: yes, size/XS

#230 Release 1.5 common files update
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#235 Fix kind
  test/e2e.sh
Labels: cla: yes, size/XS

#236 [release-1.5] Fix kind
  test/e2e.sh
Labels: cla: yes, size/XS

#233 Release 1.5 codeowners
  CODEOWNERS
  LICENSE
  README.md
  common/.commonfiles.sha
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
  test/install_k8s_test.go
Labels: cla: yes, size/S

#234 Automator: update common-files@master in istio/cni@master
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: cla: yes, size/M

#238 Update common file to 1.5 branch
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#239 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/scripts/lint_go.sh
Labels: cla: yes, size/XS
