Repository istio/cni, pull requests merged in 2020-04, with the labels that each got.

#286 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#288 inbound port carries all inbound traffic
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/S

#287 align iptables args with non-cni
  cmd/istio-cni/kubernetes.go
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cla: yes, size/M

#289 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#283 [release-1.5] fix inboundport annotation when it is empty
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cla: yes, size/M

#290 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#291 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#292 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#294 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#295 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#296 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#297 Remove namespace from clusterrole and clusterrolebinding
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, ok-to-test, size/XS

#298 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#278 Pod creation fails on OpenShift 4.3.5 with Istio 1.4.6
  Makefile.core.mk
  README.md
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/scripts/install-cni.sh
Labels: cla: yes, size/L

#299 Redirect: add 15090 to excludeInboundPorts
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cherrypick/release-1.5, cla: yes, size/M

#300 [release-1.5] Redirect: add 15090 to excludeInboundPorts
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cla: yes, size/M

#301 [release-1.4] Backport required missing fields to cni helm charts
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cla: yes, size/XS

#302 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#303 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#304 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#305 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#306 Add a note for the exclude_namespaces condition in README
  README.md
Labels: cla: yes, size/XS

#307 Update common file to 1.6 branch
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#308 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#309 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#310 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS
