Repository istio/cni, pull requests merged in 2020-05, with the labels that each got.

#312 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#311 [release-1.5] Add missing required CNI fields to helm charts for Openshift 4.3.5
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
Labels: cla: yes, flag/needs-release-note, size/XS

#313 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#314 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#315 Automator: update common-files@release-1.6 in istio/cni@release-1.6
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#316 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#317 Automator: update common-files@release-1.6 in istio/cni@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#318 Automator: update common-files@release-1.5 in istio/cni@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#319 More default exlusion ports
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cherrypick/release-1.6, cla: yes, size/M

#320 [release-1.6] More default exlusion ports
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cla: yes, size/M

#322 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#326 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#327 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#323 Reworking ipv6 detection logic
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/S

#321 Fixing cos_containerd mounting repair binary with noexec
  deployments/kubernetes/Dockerfile.install-cni
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/XS

#329 [release-1.4] Fixing cos_containerd mounting repair binary with noexec
  deployments/kubernetes/Dockerfile.install-cni
Labels: cla: yes, size/XS

#328 [release-1.6] Fixing cos_containerd mounting repair binary with noexec
  deployments/kubernetes/Dockerfile.install-cni
Labels: cla: yes, size/XS

#333 [release-1.6] Reworking ipv6 detection logic
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/S

#331 [release-1.4] Reworking ipv6 detection logic
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, size/S

#334 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#330 [release-1.5] Fixing cos_containerd mounting repair binary with noexec
  deployments/kubernetes/Dockerfile.install-cni
Labels: cla: yes, flag/needs-release-note, size/XS

#332 [release-1.5] Reworking ipv6 detection logic
  tools/packaging/common/istio-iptables.sh
Labels: cla: yes, flag/needs-release-note, size/S
