Repository istio/cni, pull requests merged in 2020-03, with the labels that each got.

#260 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#261 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#262 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#263 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#264 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#265 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#268 Ignore out/ directory
  .gitignore
Labels: cla: yes, size/XS

#267 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#269 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#270 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#271 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#272 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#273 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#274 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#275 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#277 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#276 Automator: update common-files@release-1.5 in istio/cni@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#279 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#280 istio-iptables: Replace socket match with conntrack match
  tools/packaging/common/istio-iptables.sh
Labels: cherrypick/release-1.5, cla: yes, ok-to-test, size/XS

#282 fix inboundport annotation when it is empty
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/M

#284 [release-1.4] fix inboundport annotation when it is not set
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  cmd/istio-cni/redirect.go
Labels: cla: yes, size/M
