Repository istio/cni, pull requests merged in 2020-06, with the labels that each got.

#335 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#336 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#337 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#338 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#339 add vendor dir to .gitignore
  .gitignore
Labels: cla: yes, size/XS

#340 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#341 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#342 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#343 Add a note about deprecation of this repo
  README.md
Labels: cla: yes, size/XS
