Repository istio/cni, pull requests merged in 2020-02, with the labels that each got.

#241 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#240 Adding CNI repair to 1.4
  Makefile.core.mk
  cmd/istio-cni-repair/README.md
  cmd/istio-cni-repair/main.go
  deployments/kubernetes/Dockerfile.install-cni
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  go.mod
  go.sum
  licenses/github.com/docopt/docopt-go/LICENSE
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
  tools/istio-cni-docker.mk
Labels: cla: yes, size/XXL

#242 Automator: update common-files@master in istio/cni@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#243 Changing default istio validation container name
  cmd/istio-cni-repair/main.go
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/M

#244 [release-1.4] Changing default istio validation container name
  cmd/istio-cni-repair/main.go
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
Labels: cla: yes, size/M

#245 [release-1.5] Changing default istio validation container name
  cmd/istio-cni-repair/main.go
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
Labels: cla: yes, size/M

#246 Watch-based repair controller
  cmd/istio-cni-repair/main.go
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  go.mod
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
  pkg/repair/repaircontroller.go
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/L

#237 Add ability to deploy config file standalone (not chained)
  Makefile.core.mk
  README.md
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/scripts/install-cni.sh
Labels: cherrypick/release-1.5, cla: yes, size/L

#247 [release-1.4] Watch-based repair controller
  cmd/istio-cni-repair/main.go
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  go.mod
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
  pkg/repair/repaircontroller.go
Labels: cla: yes, size/L

#249 [release-1.5] Add ability to deploy config file standalone (not chained)
  Makefile.core.mk
  README.md
  cmd/istio-cni/main.go
  cmd/istio-cni/main_test.go
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/scripts/install-cni.sh
Labels: cla: yes, size/L

#250 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#251 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#248 [release-1.5] Watch-based repair controller
  cmd/istio-cni-repair/main.go
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  go.mod
  pkg/repair/repair.go
  pkg/repair/repair_test.go
  pkg/repair/repair_test_helpers.go
  pkg/repair/repaircontroller.go
Labels: cla: yes, size/L

#254 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#255 [release-1.5] Updating CNI helm templates
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
Labels: cla: yes, size/XS

#253 Removing redundant helm charts (istio/istio is source of truth now)
  deployments/kubernetes/install/helm/.helmignore
  deployments/kubernetes/install/helm/istio-cni/Chart.yaml
  deployments/kubernetes/install/helm/istio-cni/templates/_labels.tpl
  deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
  deployments/kubernetes/install/helm/istio-cni/values.yaml
  deployments/kubernetes/install/helm/istio-cni/values_gke.yaml
Labels: cla: yes, size/L

#257 #20044 Adding graceful exit trap to install-cni.sh
  deployments/kubernetes/install/scripts/install-cni.sh
Labels: cla: yes, size/XS

#258 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#259 Automator: update common-files@master in istio/cni@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS
